/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AiPlansRouteImport } from './routes/ai-plans'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as DietsRouteImport } from './routes/diets'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as FoodItemsRouteImport } from './routes/food-items'
import { Route as JoinRequestsRouteImport } from './routes/join-requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RevenueShareRouteImport } from './routes/revenue-share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as DietsIndexRouteImport } from './routes/diets.index'
import { Route as DietsIdRouteImport } from './routes/diets.$id'
import { Route as DietsNewRouteImport } from './routes/diets.new'
import { Route as GymsIndexRouteImport } from './routes/gyms.index'
import { Route as GymsIdRouteImport } from './routes/gyms.$id'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as DietsIdIndexRouteImport } from './routes/diets.$id.index'
import { Route as DietsIdEditRouteImport } from './routes/diets.$id.edit'
import { Route as DietsIdMembersRouteImport } from './routes/diets.$id.members'
import { Route as WorkoutsIdIndexRouteImport } from './routes/workouts.$id.index'
import { Route as WorkoutsIdEditRouteImport } from './routes/workouts.$id.edit'
import { Route as WorkoutsIdMembersRouteImport } from './routes/workouts.$id.members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlansRoute = AiPlansRouteImport.update({
  id: '/ai-plans',
  path: '/ai-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DietsRoute = DietsRouteImport.update({
  id: '/diets',
  path: '/diets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodItemsRoute = FoodItemsRouteImport.update({
  id: '/food-items',
  path: '/food-items',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRequestsRoute = JoinRequestsRouteImport.update({
  id: '/join-requests',
  path: '/join-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueShareRoute = RevenueShareRouteImport.update({
  id: '/revenue-share',
  path: '/revenue-share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const DietsIndexRoute = DietsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DietsRoute,
} as any)
const DietsIdRoute = DietsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DietsRoute,
} as any)
const DietsNewRoute = DietsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DietsRoute,
} as any)
const GymsIndexRoute = GymsIndexRouteImport.update({
  id: '/gyms/',
  path: '/gyms/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymsIdRoute = GymsIdRouteImport.update({
  id: '/gyms/$id',
  path: '/gyms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkoutsRoute,
} as any)
const DietsIdIndexRoute = DietsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DietsIdRoute,
} as any)
const DietsIdEditRoute = DietsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DietsIdRoute,
} as any)
const DietsIdMembersRoute = DietsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DietsIdRoute,
} as any)
const WorkoutsIdIndexRoute = WorkoutsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsIdRoute,
} as any)
const WorkoutsIdEditRoute = WorkoutsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorkoutsIdRoute,
} as any)
const WorkoutsIdMembersRoute = WorkoutsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => WorkoutsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/ai-plans': typeof AiPlansRoute
  '/audit-logs': typeof AuditLogsRoute
  '/diets': typeof DietsRouteWithChildren
  '/exercises': typeof ExercisesRoute
  '/food-items': typeof FoodItemsRoute
  '/join-requests': typeof JoinRequestsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/revenue-share': typeof RevenueShareRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/diets/$id': typeof DietsIdRouteWithChildren
  '/diets/new': typeof DietsNewRoute
  '/gyms/$id': typeof GymsIdRoute
  '/members/$id': typeof MembersIdRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/new': typeof WorkoutsNewRoute
  '/diets/': typeof DietsIndexRoute
  '/gyms/': typeof GymsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/diets/$id/edit': typeof DietsIdEditRoute
  '/diets/$id/members': typeof DietsIdMembersRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/members': typeof WorkoutsIdMembersRoute
  '/diets/$id/': typeof DietsIdIndexRoute
  '/workouts/$id/': typeof WorkoutsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/ai-plans': typeof AiPlansRoute
  '/audit-logs': typeof AuditLogsRoute
  '/exercises': typeof ExercisesRoute
  '/food-items': typeof FoodItemsRoute
  '/join-requests': typeof JoinRequestsRoute
  '/login': typeof LoginRoute
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/revenue-share': typeof RevenueShareRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/diets/new': typeof DietsNewRoute
  '/gyms/$id': typeof GymsIdRoute
  '/members/$id': typeof MembersIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/diets': typeof DietsIndexRoute
  '/gyms': typeof GymsIndexRoute
  '/members': typeof MembersIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/diets/$id/edit': typeof DietsIdEditRoute
  '/diets/$id/members': typeof DietsIdMembersRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/members': typeof WorkoutsIdMembersRoute
  '/diets/$id': typeof DietsIdIndexRoute
  '/workouts/$id': typeof WorkoutsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/ai-plans': typeof AiPlansRoute
  '/audit-logs': typeof AuditLogsRoute
  '/diets': typeof DietsRouteWithChildren
  '/exercises': typeof ExercisesRoute
  '/food-items': typeof FoodItemsRoute
  '/join-requests': typeof JoinRequestsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/payouts': typeof PayoutsRoute
  '/profile': typeof ProfileRoute
  '/revenue-share': typeof RevenueShareRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/diets/$id': typeof DietsIdRouteWithChildren
  '/diets/new': typeof DietsNewRoute
  '/gyms/$id': typeof GymsIdRoute
  '/members/$id': typeof MembersIdRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/new': typeof WorkoutsNewRoute
  '/diets/': typeof DietsIndexRoute
  '/gyms/': typeof GymsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/diets/$id/edit': typeof DietsIdEditRoute
  '/diets/$id/members': typeof DietsIdMembersRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/members': typeof WorkoutsIdMembersRoute
  '/diets/$id/': typeof DietsIdIndexRoute
  '/workouts/$id/': typeof WorkoutsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/ai-plans'
    | '/audit-logs'
    | '/diets'
    | '/exercises'
    | '/food-items'
    | '/join-requests'
    | '/login'
    | '/members'
    | '/payouts'
    | '/profile'
    | '/revenue-share'
    | '/settings'
    | '/subscriptions'
    | '/workouts'
    | '/diets/$id'
    | '/diets/new'
    | '/gyms/$id'
    | '/members/$id'
    | '/workouts/$id'
    | '/workouts/new'
    | '/diets/'
    | '/gyms/'
    | '/members/'
    | '/workouts/'
    | '/diets/$id/edit'
    | '/diets/$id/members'
    | '/workouts/$id/edit'
    | '/workouts/$id/members'
    | '/diets/$id/'
    | '/workouts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/ai-plans'
    | '/audit-logs'
    | '/exercises'
    | '/food-items'
    | '/join-requests'
    | '/login'
    | '/payouts'
    | '/profile'
    | '/revenue-share'
    | '/settings'
    | '/subscriptions'
    | '/diets/new'
    | '/gyms/$id'
    | '/members/$id'
    | '/workouts/new'
    | '/diets'
    | '/gyms'
    | '/members'
    | '/workouts'
    | '/diets/$id/edit'
    | '/diets/$id/members'
    | '/workouts/$id/edit'
    | '/workouts/$id/members'
    | '/diets/$id'
    | '/workouts/$id'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/ai-plans'
    | '/audit-logs'
    | '/diets'
    | '/exercises'
    | '/food-items'
    | '/join-requests'
    | '/login'
    | '/members'
    | '/payouts'
    | '/profile'
    | '/revenue-share'
    | '/settings'
    | '/subscriptions'
    | '/workouts'
    | '/diets/$id'
    | '/diets/new'
    | '/gyms/$id'
    | '/members/$id'
    | '/workouts/$id'
    | '/workouts/new'
    | '/diets/'
    | '/gyms/'
    | '/members/'
    | '/workouts/'
    | '/diets/$id/edit'
    | '/diets/$id/members'
    | '/workouts/$id/edit'
    | '/workouts/$id/members'
    | '/diets/$id/'
    | '/workouts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  AiPlansRoute: typeof AiPlansRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DietsRoute: typeof DietsRouteWithChildren
  ExercisesRoute: typeof ExercisesRoute
  FoodItemsRoute: typeof FoodItemsRoute
  JoinRequestsRoute: typeof JoinRequestsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  PayoutsRoute: typeof PayoutsRoute
  ProfileRoute: typeof ProfileRoute
  RevenueShareRoute: typeof RevenueShareRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
  GymsIdRoute: typeof GymsIdRoute
  GymsIndexRoute: typeof GymsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-plans': {
      id: '/ai-plans'
      path: '/ai-plans'
      fullPath: '/ai-plans'
      preLoaderRoute: typeof AiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diets': {
      id: '/diets'
      path: '/diets'
      fullPath: '/diets'
      preLoaderRoute: typeof DietsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-items': {
      id: '/food-items'
      path: '/food-items'
      fullPath: '/food-items'
      preLoaderRoute: typeof FoodItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-requests': {
      id: '/join-requests'
      path: '/join-requests'
      fullPath: '/join-requests'
      preLoaderRoute: typeof JoinRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-share': {
      id: '/revenue-share'
      path: '/revenue-share'
      fullPath: '/revenue-share'
      preLoaderRoute: typeof RevenueShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diets/': {
      id: '/diets/'
      path: '/'
      fullPath: '/diets/'
      preLoaderRoute: typeof DietsIndexRouteImport
      parentRoute: typeof DietsRoute
    }
    '/diets/$id': {
      id: '/diets/$id'
      path: '/$id'
      fullPath: '/diets/$id'
      preLoaderRoute: typeof DietsIdRouteImport
      parentRoute: typeof DietsRoute
    }
    '/diets/new': {
      id: '/diets/new'
      path: '/new'
      fullPath: '/diets/new'
      preLoaderRoute: typeof DietsNewRouteImport
      parentRoute: typeof DietsRoute
    }
    '/gyms/': {
      id: '/gyms/'
      path: '/gyms'
      fullPath: '/gyms/'
      preLoaderRoute: typeof GymsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gyms/$id': {
      id: '/gyms/$id'
      path: '/gyms/$id'
      fullPath: '/gyms/$id'
      preLoaderRoute: typeof GymsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/diets/$id/': {
      id: '/diets/$id/'
      path: '/'
      fullPath: '/diets/$id/'
      preLoaderRoute: typeof DietsIdIndexRouteImport
      parentRoute: typeof DietsIdRoute
    }
    '/diets/$id/edit': {
      id: '/diets/$id/edit'
      path: '/edit'
      fullPath: '/diets/$id/edit'
      preLoaderRoute: typeof DietsIdEditRouteImport
      parentRoute: typeof DietsIdRoute
    }
    '/diets/$id/members': {
      id: '/diets/$id/members'
      path: '/members'
      fullPath: '/diets/$id/members'
      preLoaderRoute: typeof DietsIdMembersRouteImport
      parentRoute: typeof DietsIdRoute
    }
    '/workouts/$id/': {
      id: '/workouts/$id/'
      path: '/'
      fullPath: '/workouts/$id/'
      preLoaderRoute: typeof WorkoutsIdIndexRouteImport
      parentRoute: typeof WorkoutsIdRoute
    }
    '/workouts/$id/edit': {
      id: '/workouts/$id/edit'
      path: '/edit'
      fullPath: '/workouts/$id/edit'
      preLoaderRoute: typeof WorkoutsIdEditRouteImport
      parentRoute: typeof WorkoutsIdRoute
    }
    '/workouts/$id/members': {
      id: '/workouts/$id/members'
      path: '/members'
      fullPath: '/workouts/$id/members'
      preLoaderRoute: typeof WorkoutsIdMembersRouteImport
      parentRoute: typeof WorkoutsIdRoute
    }
  }
}

interface DietsIdRouteChildren {
  DietsIdEditRoute: typeof DietsIdEditRoute
  DietsIdMembersRoute: typeof DietsIdMembersRoute
  DietsIdIndexRoute: typeof DietsIdIndexRoute
}

const DietsIdRouteChildren: DietsIdRouteChildren = {
  DietsIdEditRoute: DietsIdEditRoute,
  DietsIdMembersRoute: DietsIdMembersRoute,
  DietsIdIndexRoute: DietsIdIndexRoute,
}

const DietsIdRouteWithChildren =
  DietsIdRoute._addFileChildren(DietsIdRouteChildren)

interface DietsRouteChildren {
  DietsIdRoute: typeof DietsIdRouteWithChildren
  DietsNewRoute: typeof DietsNewRoute
  DietsIndexRoute: typeof DietsIndexRoute
}

const DietsRouteChildren: DietsRouteChildren = {
  DietsIdRoute: DietsIdRouteWithChildren,
  DietsNewRoute: DietsNewRoute,
  DietsIndexRoute: DietsIndexRoute,
}

const DietsRouteWithChildren = DietsRoute._addFileChildren(DietsRouteChildren)

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface WorkoutsIdRouteChildren {
  WorkoutsIdEditRoute: typeof WorkoutsIdEditRoute
  WorkoutsIdMembersRoute: typeof WorkoutsIdMembersRoute
  WorkoutsIdIndexRoute: typeof WorkoutsIdIndexRoute
}

const WorkoutsIdRouteChildren: WorkoutsIdRouteChildren = {
  WorkoutsIdEditRoute: WorkoutsIdEditRoute,
  WorkoutsIdMembersRoute: WorkoutsIdMembersRoute,
  WorkoutsIdIndexRoute: WorkoutsIdIndexRoute,
}

const WorkoutsIdRouteWithChildren = WorkoutsIdRoute._addFileChildren(
  WorkoutsIdRouteChildren,
)

interface WorkoutsRouteChildren {
  WorkoutsIdRoute: typeof WorkoutsIdRouteWithChildren
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsIdRoute: WorkoutsIdRouteWithChildren,
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  AiPlansRoute: AiPlansRoute,
  AuditLogsRoute: AuditLogsRoute,
  DietsRoute: DietsRouteWithChildren,
  ExercisesRoute: ExercisesRoute,
  FoodItemsRoute: FoodItemsRoute,
  JoinRequestsRoute: JoinRequestsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  PayoutsRoute: PayoutsRoute,
  ProfileRoute: ProfileRoute,
  RevenueShareRoute: RevenueShareRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
  GymsIdRoute: GymsIdRoute,
  GymsIndexRoute: GymsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
